//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRNegocio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public decimal CL_ID { get; set; }
        public string CL_RUT { get; set; }
        public string CL_NOMBRE { get; set; }
        public string CL_APELLIDOP { get; set; }
        public string CL_APELLIDOM { get; set; }
        public System.DateTime CL_FECHANAC { get; set; }
        public string CL_EMAIL { get; set; }
        public decimal CL_FONO { get; set; }
        public System.DateTime CL_FECHA_REGISTRO { get; set; }
        public string CL_CLAVE { get; set; }
        public string CL_ESTADO { get; set; }
        public Nullable<decimal> CL_MULTAS { get; set; }
        public string CL_RESERVA { get; set; }
    }
}
