//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRNegocio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int IDEMPLEADO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string CEDULA { get; set; }
        public decimal EDAD { get; set; }
    }
}
