//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRNegocio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public decimal FUNC_ID { get; set; }
        public string FUNC_RUT { get; set; }
        public string FUNC_NOMBRE { get; set; }
        public string FUNC_APELLIDOP { get; set; }
        public string FUNC_APELLIDOM { get; set; }
        public System.DateTime FUNC_FECHANAC { get; set; }
        public string FUNC_EMAIL { get; set; }
        public long FUNC_FONO { get; set; }
        public System.DateTime FUNC_FECHA_INGRESO { get; set; }
        public string FUNC_CLAVE { get; set; }
        public Nullable<decimal> FUNC_IDROL { get; set; }
        public string FUNC_ESTADO { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
